*** Settings ***
Documentation     This common variables file has all the common variables


*** Variables ***
${BASE_URL}    https://vlmsdev.valgenesis.in/VGV5DEV/Login/Login.aspx
${BROWSER_NAME}    chrome
${SUPER_ADMIN}    superadmin_01
${SUPER_ADMIN_PASSWORD}    valgen
${USER}    qzuser1
${USER_PASSWORD}    valgen
${SHORT_WAIT}    5
${MEDIUM_WAIT}    20
${LONG_WAIT}    40
${TESTDATA_FOLDER}    ${EXECDIR}\\Testdata\\Testdata.xlsx
${SCREENSHOT}    True
${VIDEO}    False
